project:
  type: website
  output-dir: docs

website:
  title: "Florence Ghestem"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: iges-supplementary-materials.qmd
        text: IGES Supplementary Materials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true