project:
  type: website
  output-dir: docs

website:
  title: "Florence Ghestem"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: Resume
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full